/* Auto-generated by genmsg_cpp for file /var/tmp/hark_msgs/msg/HarkSourceVal.msg */
#ifndef HARK_MSGS_MESSAGE_HARKSOURCEVAL_H
#define HARK_MSGS_MESSAGE_HARKSOURCEVAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace hark_msgs
{
template <class ContainerAllocator>
struct HarkSourceVal_ {
  typedef HarkSourceVal_<ContainerAllocator> Type;

  HarkSourceVal_()
  : id(0)
  , power(0.0)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , theta(0.0)
  {
  }

  HarkSourceVal_(const ContainerAllocator& _alloc)
  : id(0)
  , power(0.0)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , theta(0.0)
  {
  }

  typedef int32_t _id_type;
  int32_t id;

  typedef float _power_type;
  float power;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;

  typedef float _theta_type;
  float theta;


  typedef boost::shared_ptr< ::hark_msgs::HarkSourceVal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hark_msgs::HarkSourceVal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HarkSourceVal
typedef  ::hark_msgs::HarkSourceVal_<std::allocator<void> > HarkSourceVal;

typedef boost::shared_ptr< ::hark_msgs::HarkSourceVal> HarkSourceValPtr;
typedef boost::shared_ptr< ::hark_msgs::HarkSourceVal const> HarkSourceValConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hark_msgs::HarkSourceVal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hark_msgs::HarkSourceVal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hark_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hark_msgs::HarkSourceVal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hark_msgs::HarkSourceVal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hark_msgs::HarkSourceVal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "345ac858b579f456018a341667376f28";
  }

  static const char* value(const  ::hark_msgs::HarkSourceVal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x345ac858b579f456ULL;
  static const uint64_t static_value2 = 0x018a341667376f28ULL;
};

template<class ContainerAllocator>
struct DataType< ::hark_msgs::HarkSourceVal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hark_msgs/HarkSourceVal";
  }

  static const char* value(const  ::hark_msgs::HarkSourceVal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hark_msgs::HarkSourceVal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 id\n\
float32 power\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 theta\n\
\n\
";
  }

  static const char* value(const  ::hark_msgs::HarkSourceVal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hark_msgs::HarkSourceVal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hark_msgs::HarkSourceVal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
    stream.next(m.power);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.theta);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HarkSourceVal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hark_msgs::HarkSourceVal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hark_msgs::HarkSourceVal_<ContainerAllocator> & v) 
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "power: ";
    Printer<float>::stream(s, indent + "  ", v.power);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HARK_MSGS_MESSAGE_HARKSOURCEVAL_H

