/* Auto-generated by genmsg_cpp for file /var/tmp/hark_msgs/msg/HarkInt.msg */
#ifndef HARK_MSGS_MESSAGE_HARKINT_H
#define HARK_MSGS_MESSAGE_HARKINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace hark_msgs
{
template <class ContainerAllocator>
struct HarkInt_ {
  typedef HarkInt_<ContainerAllocator> Type;

  HarkInt_()
  : data(0)
  {
  }

  HarkInt_(const ContainerAllocator& _alloc)
  : data(0)
  {
  }

  typedef int64_t _data_type;
  int64_t data;


  typedef boost::shared_ptr< ::hark_msgs::HarkInt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hark_msgs::HarkInt_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HarkInt
typedef  ::hark_msgs::HarkInt_<std::allocator<void> > HarkInt;

typedef boost::shared_ptr< ::hark_msgs::HarkInt> HarkIntPtr;
typedef boost::shared_ptr< ::hark_msgs::HarkInt const> HarkIntConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hark_msgs::HarkInt_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hark_msgs::HarkInt_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hark_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hark_msgs::HarkInt_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hark_msgs::HarkInt_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hark_msgs::HarkInt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "34add168574510e6e17f5d23ecc077ef";
  }

  static const char* value(const  ::hark_msgs::HarkInt_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x34add168574510e6ULL;
  static const uint64_t static_value2 = 0xe17f5d23ecc077efULL;
};

template<class ContainerAllocator>
struct DataType< ::hark_msgs::HarkInt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hark_msgs/HarkInt";
  }

  static const char* value(const  ::hark_msgs::HarkInt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hark_msgs::HarkInt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 data\n\
\n\
";
  }

  static const char* value(const  ::hark_msgs::HarkInt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hark_msgs::HarkInt_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hark_msgs::HarkInt_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HarkInt_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hark_msgs::HarkInt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hark_msgs::HarkInt_<ContainerAllocator> & v) 
  {
    s << indent << "data: ";
    Printer<int64_t>::stream(s, indent + "  ", v.data);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HARK_MSGS_MESSAGE_HARKINT_H

