/* Auto-generated by genmsg_cpp for file /var/tmp/hark_msgs/msg/HarkSrcFFTVal.msg */
#ifndef HARK_MSGS_MESSAGE_HARKSRCFFTVAL_H
#define HARK_MSGS_MESSAGE_HARKSRCFFTVAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace hark_msgs
{
template <class ContainerAllocator>
struct HarkSrcFFTVal_ {
  typedef HarkSrcFFTVal_<ContainerAllocator> Type;

  HarkSrcFFTVal_()
  : id(0)
  , power(0.0)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , theta(0.0)
  , length(0)
  , fftdata_real()
  , fftdata_imag()
  {
  }

  HarkSrcFFTVal_(const ContainerAllocator& _alloc)
  : id(0)
  , power(0.0)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , theta(0.0)
  , length(0)
  , fftdata_real(_alloc)
  , fftdata_imag(_alloc)
  {
  }

  typedef int32_t _id_type;
  int32_t id;

  typedef float _power_type;
  float power;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;

  typedef float _theta_type;
  float theta;

  typedef int32_t _length_type;
  int32_t length;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _fftdata_real_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  fftdata_real;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _fftdata_imag_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  fftdata_imag;


  typedef boost::shared_ptr< ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HarkSrcFFTVal
typedef  ::hark_msgs::HarkSrcFFTVal_<std::allocator<void> > HarkSrcFFTVal;

typedef boost::shared_ptr< ::hark_msgs::HarkSrcFFTVal> HarkSrcFFTValPtr;
typedef boost::shared_ptr< ::hark_msgs::HarkSrcFFTVal const> HarkSrcFFTValConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hark_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "72eece3323d7e19f303a85adc3c97970";
  }

  static const char* value(const  ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x72eece3323d7e19fULL;
  static const uint64_t static_value2 = 0x303a85adc3c97970ULL;
};

template<class ContainerAllocator>
struct DataType< ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hark_msgs/HarkSrcFFTVal";
  }

  static const char* value(const  ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 id\n\
float32 power\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 theta\n\
int32 length\n\
float32[] fftdata_real\n\
float32[] fftdata_imag\n\
\n\
";
  }

  static const char* value(const  ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
    stream.next(m.power);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.theta);
    stream.next(m.length);
    stream.next(m.fftdata_real);
    stream.next(m.fftdata_imag);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HarkSrcFFTVal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hark_msgs::HarkSrcFFTVal_<ContainerAllocator> & v) 
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "power: ";
    Printer<float>::stream(s, indent + "  ", v.power);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "length: ";
    Printer<int32_t>::stream(s, indent + "  ", v.length);
    s << indent << "fftdata_real[]" << std::endl;
    for (size_t i = 0; i < v.fftdata_real.size(); ++i)
    {
      s << indent << "  fftdata_real[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.fftdata_real[i]);
    }
    s << indent << "fftdata_imag[]" << std::endl;
    for (size_t i = 0; i < v.fftdata_imag.size(); ++i)
    {
      s << indent << "  fftdata_imag[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.fftdata_imag[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // HARK_MSGS_MESSAGE_HARKSRCFFTVAL_H

