/* Auto-generated by genmsg_cpp for file /var/tmp/fdopencv_msgs/msg/ImageMap.msg */
#ifndef FDOPENCV_MSGS_MESSAGE_IMAGEMAP_H
#define FDOPENCV_MSGS_MESSAGE_IMAGEMAP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "fdopencv_msgs/ImageMapVal.h"

namespace fdopencv_msgs
{
template <class ContainerAllocator>
struct ImageMap_ {
  typedef ImageMap_<ContainerAllocator> Type;

  ImageMap_()
  : header()
  , count(0)
  , num(0)
  , src()
  {
  }

  ImageMap_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , count(0)
  , num(0)
  , src(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _count_type;
  int32_t count;

  typedef int32_t _num_type;
  int32_t num;

  typedef std::vector< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >::other >  _src_type;
  std::vector< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >::other >  src;


  typedef boost::shared_ptr< ::fdopencv_msgs::ImageMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fdopencv_msgs::ImageMap_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ImageMap
typedef  ::fdopencv_msgs::ImageMap_<std::allocator<void> > ImageMap;

typedef boost::shared_ptr< ::fdopencv_msgs::ImageMap> ImageMapPtr;
typedef boost::shared_ptr< ::fdopencv_msgs::ImageMap const> ImageMapConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::fdopencv_msgs::ImageMap_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::fdopencv_msgs::ImageMap_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace fdopencv_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::fdopencv_msgs::ImageMap_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::fdopencv_msgs::ImageMap_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::fdopencv_msgs::ImageMap_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5b7f3665db92b0de9828f481864a0838";
  }

  static const char* value(const  ::fdopencv_msgs::ImageMap_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5b7f3665db92b0deULL;
  static const uint64_t static_value2 = 0x9828f481864a0838ULL;
};

template<class ContainerAllocator>
struct DataType< ::fdopencv_msgs::ImageMap_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fdopencv_msgs/ImageMap";
  }

  static const char* value(const  ::fdopencv_msgs::ImageMap_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::fdopencv_msgs::ImageMap_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 count\n\
int32 num         # number of map members\n\
ImageMapVal[] src # Images in the map\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: fdopencv_msgs/ImageMapVal\n\
int32 id\n\
sensor_msgs/Image img\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
";
  }

  static const char* value(const  ::fdopencv_msgs::ImageMap_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::fdopencv_msgs::ImageMap_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::fdopencv_msgs::ImageMap_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::fdopencv_msgs::ImageMap_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.count);
    stream.next(m.num);
    stream.next(m.src);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ImageMap_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fdopencv_msgs::ImageMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::fdopencv_msgs::ImageMap_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    s << indent << "src[]" << std::endl;
    for (size_t i = 0; i < v.src.size(); ++i)
    {
      s << indent << "  src[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fdopencv_msgs::ImageMapVal_<ContainerAllocator> >::stream(s, indent + "    ", v.src[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // FDOPENCV_MSGS_MESSAGE_IMAGEMAP_H

