"""autogenerated by genpy from hark_msgs/HarkJulius.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hark_msgs.msg
import std_msgs.msg

class HarkJulius(genpy.Message):
  _md5sum = "18ac98bafa65529bae1ef5042e324284"
  _type = "hark_msgs/HarkJulius"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
HarkJuliusSrc[] src # Detail of Julius recognition result

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: hark_msgs/HarkJuliusSrc
int32 id
float32 azimuth
float32 elevation
int32 sec
int32 usec
int32 frames
int32 msec
int8 status            # status of recognition process defined below
HarkJuliusSrcVal[] src # WHYPO results for each source

int8 TERMINATED=0
int8 STARTRECOG=1
int8 INPUTPARAM=2
int8 SOURCEINFO=3
int8 RECOGOUT=4
int8 RECOGFAIL=5

================================================================================
MSG: hark_msgs/HarkJuliusSrcVal
string word
int32 classid
string phone
float32 cm

"""
  __slots__ = ['header','src']
  _slot_types = ['std_msgs/Header','hark_msgs/HarkJuliusSrc[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,src

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HarkJulius, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.src is None:
        self.src = []
    else:
      self.header = std_msgs.msg.Header()
      self.src = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.src)
      buff.write(_struct_I.pack(length))
      for val1 in self.src:
        _x = val1
        buff.write(_struct_i2f4ib.pack(_x.id, _x.azimuth, _x.elevation, _x.sec, _x.usec, _x.frames, _x.msec, _x.status))
        length = len(val1.src)
        buff.write(_struct_I.pack(length))
        for val2 in val1.src:
          _x = val2.word
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          buff.write(_struct_i.pack(val2.classid))
          _x = val2.phone
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          buff.write(_struct_f.pack(val2.cm))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.src is None:
        self.src = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.src = []
      for i in range(0, length):
        val1 = hark_msgs.msg.HarkJuliusSrc()
        _x = val1
        start = end
        end += 29
        (_x.id, _x.azimuth, _x.elevation, _x.sec, _x.usec, _x.frames, _x.msec, _x.status,) = _struct_i2f4ib.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.src = []
        for i in range(0, length):
          val2 = hark_msgs.msg.HarkJuliusSrcVal()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.word = str[start:end].decode('utf-8')
          else:
            val2.word = str[start:end]
          start = end
          end += 4
          (val2.classid,) = _struct_i.unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.phone = str[start:end].decode('utf-8')
          else:
            val2.phone = str[start:end]
          start = end
          end += 4
          (val2.cm,) = _struct_f.unpack(str[start:end])
          val1.src.append(val2)
        self.src.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.src)
      buff.write(_struct_I.pack(length))
      for val1 in self.src:
        _x = val1
        buff.write(_struct_i2f4ib.pack(_x.id, _x.azimuth, _x.elevation, _x.sec, _x.usec, _x.frames, _x.msec, _x.status))
        length = len(val1.src)
        buff.write(_struct_I.pack(length))
        for val2 in val1.src:
          _x = val2.word
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          buff.write(_struct_i.pack(val2.classid))
          _x = val2.phone
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.pack('<I%ss'%length, length, _x))
          buff.write(_struct_f.pack(val2.cm))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.src is None:
        self.src = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.src = []
      for i in range(0, length):
        val1 = hark_msgs.msg.HarkJuliusSrc()
        _x = val1
        start = end
        end += 29
        (_x.id, _x.azimuth, _x.elevation, _x.sec, _x.usec, _x.frames, _x.msec, _x.status,) = _struct_i2f4ib.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.src = []
        for i in range(0, length):
          val2 = hark_msgs.msg.HarkJuliusSrcVal()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.word = str[start:end].decode('utf-8')
          else:
            val2.word = str[start:end]
          start = end
          end += 4
          (val2.classid,) = _struct_i.unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.phone = str[start:end].decode('utf-8')
          else:
            val2.phone = str[start:end]
          start = end
          end += 4
          (val2.cm,) = _struct_f.unpack(str[start:end])
          val1.src.append(val2)
        self.src.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_3I = struct.Struct("<3I")
_struct_i2f4ib = struct.Struct("<i2f4ib")
_struct_f = struct.Struct("<f")
